# Generated by Django 6.0.3 on 2026-04-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(help_text='Позиция X в процентах (0-100)')),
                ('position_y', models.FloatField(help_text='Позиция Y в процентах (0-100)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Кликабельная точка',
                'verbose_name_plural': 'Кликабельные точки',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='lookbook/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главный образ')),
                ('products', models.ManyToManyField(related_name='lookbooks', through='lookbook.Hotspot', to='shop.product')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Lookbook',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='hotspot',
            name='lookbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='lookbook.lookbookitem'),
        ),
    ]
