# Generated by Django 6.0.3 on 2026-03-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_remove_product_shop_produc_id_f21274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_percent', models.FloatField(verbose_name='Координата X (%)')),
                ('y_percent', models.FloatField(verbose_name='Координата Y (%)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
            },
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название образа')),
                ('image', models.ImageField(upload_to='lookbook/%Y/%m/%d', verbose_name='Фото образа')),
                ('description', models.TextField(blank=True, verbose_name='Описание образа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('products', models.ManyToManyField(through='lookbook.Hotspot', to='shop.product')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='hotspot',
            name='lookbook_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookbook.lookbookitem'),
        ),
        migrations.AlterUniqueTogether(
            name='hotspot',
            unique_together={('lookbook_item', 'product')},
        ),
    ]
