# Generated by Django 6.0.3 on 2026-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_shop_produc_id_f21274_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, help_text='Например: 100% хлопок', max_length=300, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list, help_text='Введите список размеров, например: ["XS", "S", "M", "L"]', verbose_name='Доступные размеры'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
    ]
