# Generated by Django 6.0.3 on 2026-04-16 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='lookbook.lookbookitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_looks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный образ',
                'verbose_name_plural': 'Избранные образы',
                'unique_together': {('user', 'look')},
            },
        ),
    ]
